<?php

/**
 * @file
 * Contains hook implementations for the Puzzle Hunt Tracker module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_entity_presave().
 */
function puzzlehunt_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'puzzle':
      $currentSolvers = array_column($entity->field_current_solvers->getValue(), 'target_id');
      $historicalSolvers = array_column($entity->field_historical_solvers->getValue(), 'target_id');
      $newSolvers = array_diff($currentSolvers, $historicalSolvers);
      foreach($newSolvers as $newSolver) {
        $entity->field_historical_solvers[] = $newSolver;
      }
      break;
  }
}

/**
 * Implements hook_entity_operation().
 */
function puzzlehunt_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'node') {
    return;
  }

  $nodeType = $entity->bundle();
  $nodeId = $entity->id();
  $userId = \Drupal::currentUser()->id();
  $currentSolvers = array_column($entity->field_current_solvers->getValue(), 'target_id');

  if ($nodeType == 'puzzle') {
    if (!in_array($userId, $currentSolvers)) {
      $operations['add_solver'] = [
        'title' => t('Start Working'),
        'url' => Url::fromRoute('puzzlehunt.add_solver', ['node' => $nodeId]),
        'weight' => 0,
      ];
    }
    else {
      $operations['remove_solver'] = [
        'title' => t('Stop Working'),
        'url' => Url::fromRoute('puzzlehunt.remove_solver', ['node' => $nodeId]),
        'weight' => 1,
      ];
    }
  }

  return $operations;
}
