views.style.collapsible_list:
  type: views_style
  label: 'Collapsible List'
  mapping:
    type:
      type:  string
      label: 'List type'
    collapsible_fields:
      type:  sequence
      label: 'Collapsible fields'
      sequence:
        type: string
        label: 'Field'
    wrapper_class:
      type: string
      label: 'Wrapper class'
    class:
      type: string
      label: 'List class'
