language: php
# The Travis CI container mode has random functional test fails, so we must use
# sudo here.
sudo: true

php:
  - 5.6
  - 7
  - 7.3

env:
  global:
    # Make the script re-usable for other modules.
    - MODULE=rules
    # Allow this many deprecation warnings (total on core 8.7 at 11 Dec 2019)
    - SYMFONY_DEPRECATIONS_HELPER=11209
  matrix:
    - DRUPAL_CORE=8.7.x
    - DRUPAL_CORE=8.8.x
    - DRUPAL_CORE=8.9.x

matrix:
  fast_finish: true
  # PHP7.3 is not supported on Core 8.7 and earlier.
  # PHP5 is not supported on Core 8.8 and later.
  exclude:
    - php: 7.3
      env: DRUPAL_CORE=8.7.x
    - php: 5.6
      env: DRUPAL_CORE=8.8.x
    - php: 5.6
      env: DRUPAL_CORE=8.9.x

services:
  - mysql

mysql:
  database: $MODULE
  username: root
  encoding: utf8

# Be sure to cache composer downloads.
cache:
  directories:
    - $HOME/.composer

before_script:
  - echo $MODULE

  # Remove Xdebug as we don't need it and it causes
  # PHP Fatal error:  Maximum function nesting level of '256' reached.
  # We also don't care if that file exists or not on PHP 7.
  - phpenv config-rm xdebug.ini || true

  # Remember the current $MODULE test directory for later use in the Drupal
  # installation.
  - TESTDIR=$(pwd)
  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Create database.
  - mysql -e "create database $MODULE"
  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/$MODULE
  # Download Drupal 8 core from the Github mirror because it is faster.
  - travis_retry git clone --branch $DRUPAL_CORE --depth 1 https://github.com/drupal/drupal.git
  - cd drupal

  # Reference $MODULE in build site.
  - ln -s $TESTDIR modules/$MODULE
  # Install dependencies.
  - travis_retry git clone --branch 8.x-1.x --depth 1 https://git.drupalcode.org/project/typed_data.git modules/typed_data

  # Run composer install for Drupal 8.1 and up. We need an up-to-date composer
  # when installing Drupal 8.1.
  - travis_retry composer self-update && travis_retry composer install
  # Run composer install in the module directory in order to fetch dev
  # dependencies there. This includes phpcs & coder for checking coding style.
  - travis_retry composer install -d $TESTDIR

  # If running Core 8.6 or 8.7 the following script will upgrade to phpunit 6
  # which is required in PHP7. The script has now been deleted from Core 8.8.
  - if [[ $DRUPAL_CORE == "8.6.x" || $DRUPAL_CORE == "8.7.x" ]]; then
      travis_retry composer run-script drupal-phpunit-upgrade;
    fi

  # Start a web server on port 8888, run in the background.
  - php -S localhost:8888 &

  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://localhost:8888

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - ./vendor/bin/phpunit -c ./core/phpunit.xml.dist ./modules/$MODULE/tests/
  # Check for coding standards.
  - cd modules/$MODULE && ./vendor/bin/phpcs --colors --report-width=130
